### ISSUE TITLE
suggestion - use TCPDF library provided by GLPI for QR code and barcode generation

### ISSUE THREAD

**Issue by btry** [pluginsGLPI/barcode#1]
Hi

TCPDF is able to generate barcodes and qr codes. It would be a good idea to use it instead of other libraries, and make the plugin smaller.

**Comment by btry** [comment]
dup of #2

**Comment by ddurieux** [comment]
You are too fast, you create issue before I recreate issues from old forge :D

**Comment by btry** [comment]
sorry :)
