### ISSUE TITLE
Bug between item name displayed and qrcode

### ISSUE THREAD

**Issue by cyrakuse** [pluginsGLPI/barcode#100]
When i use the "Don't use the XX first codes" field, i don't have the same thing in the item name displayed et the item name in the QRCODE.

If i put the "Don't use the XX first codes" value at "1", the datas in the QRCODE are correct but the item name diplayed in the bottom of the QRCode is the name of the previous QRCode on the page

I use GLPI v9.5.7 with barcode v2.6.2

**Comment by cyrakuse** [comment]
Any idea on how i can resolve this problem ?

**Comment by cyrakuse** [comment]
I've found the problem.

In qrcode.class.php, you have to replace in line 367 :

`if ($ma->POST['eliminate'] > 0) {
               for ($nb=0; $nb < $ma->POST['eliminate']; $nb++) {
                  $codes[] = '';
               }
            }`

By : 

`if ($ma->POST['eliminate'] > 0) {
               for ($nb=0; $nb < $ma->POST['eliminate']; $nb++) {
                  $codes[] = '';
                  $displayDataCollection[] = '';
               }
            }`

**Comment by cedric-anne** [comment]
Hi,

Could you make a pull request with this change ?

**Comment by cyrakuse** [comment]
Sorry but don't know how to do that.
Here is the modified file.
[qrcode.class.zip](https://github.com/pluginsGLPI/barcode/files/9043852/qrcode.class.zip)
.
