### ISSUE TITLE
Problem installing (worked around)

### ISSUE THREAD

**Issue by LeeBrown** [pluginsGLPI/barcode#15]
After unzipping the plugin I see nothing in the GLPI setup/plugin page.
Renaming the directory from barcode-master to barcode fixes this, ie:

cd /usr/local/www/glpi/plugins
unzip barcode-baster.zip
mv barcode-master barcode

GLPI 9.2.1
FreeBSD 11.1-RELEASE

**Comment by ddurieux** [comment]
Yes the folder is `barcode` and not `barcodes`

**Comment by cedric-anne** [comment]
Hi,

The plugin have to be installed in a directory having same name as the plugin. So for `barcode`, the directory must be `plugins/barcode`.

Last official release archives are OK.

Regards
