### ISSUE TITLE
Network Equipment has no Barcode action

### ISSUE THREAD

**Issue by LeeBrown** [pluginsGLPI/barcode#16]
It seems Network needs to be renamed to NetworkEquipment line 49, hook.php, at least for 9.2.1

**Comment by gmed-ed** [comment]
Same with glpi 9.3.1 and V 2.2.0 for the plugin.

Thanks to LeeBrown, you have been helping a lot.

**Comment by cedric-anne** [comment]
Hi,

Will be fixed in 2.4.0 release that will be available with next GLPI 9.4 release. (see #39)

Regards
