### ISSUE TITLE
In GLPI 0.83.2 not work

### ISSUE THREAD

**Issue by darionsr** [pluginsGLPI/barcode#19]
Hi,

Im in GLPI 0.83.2 . I follow this steps:
Put the download in: /var/www/glpi/plugins
unzip barcode-baster.zip
mv barcode-master barcode

Immediately afterwards it shows me error when I go to: localhost/glpi

What am I doing wrong? I have put chmod -R 775 to 'barcode' folder.

Thanks!

**Comment by trasher** [comment]
Master requires GLPI 9.2. You have to use an old version of the pugin.

BTW; you 0.83 is really outdated, you should consider upgrading.

**Comment by darionsr** [comment]
Thank you trasher! 

I tried with 0.84 version and did not work either.  I will try to update GLPI as you say.

Thanks.
