### ISSUE TITLE
Enhancement - Custom Page Dimension

### ISSUE THREAD

**Issue by OliverTempel** [pluginsGLPI/barcode#21]
barcode has predefined Page Sizes "A4, A5,A6 ..." where can i add custom dimensions?

**Comment by cedric-anne** [comment]
Hi,

Predefined values are corresponding to predefined values supported by the library used to generate PDF file (see https://github.com/rospdf/pdf-php/blob/0.12.48/src/Cezpdf.php#L112).

It is possible to add more formats, but you will have to:
 - add a format to the dropdown used to select it (here https://github.com/pluginsGLPI/barcode/blob/2.2.0/inc/barcode.class.php#L76),
 - convert it to an array of dimensions before passing it to `Cezpdf` (here https://github.com/pluginsGLPI/barcode/blob/2.2.0/inc/barcode.class.php#L304).

Regards
