### ISSUE TITLE
Missing charset definition in header of file cs_CZ.po

### ISSUE THREAD

**Issue by p-bo** [pluginsGLPI/barcode#22]
In file locales/cs_CZ.po
(origin of file is on Transifex, file downloaded from there have the same deficiency - so it is insufficient to correct it there on Github, where is the same mistake - wrong settings on Transifex probably)

is
"Content-Type: text/plain; charset=CHARSET\n"

which leads to error in conversion to .mo :

msgfmt for_use_glpi_barcode_plugin-09010_cs_CZ.po -o for_use_glpi_barcode_plugin-09010_cs_CZ.mo

for_use_glpi_barcode_plugin-09010_cs_CZ.po: warning: Charset "CHARSET" is not a portable encoding name. Message conversion to user's charset might not work.

record should be:
"Content-Type: text/plain; charset=UTF8\n"

Thanks :)

**Comment by trasher** [comment]
Hi,

Please report this issue to Transifex; there are no settings we can change as far as I know (and this kind of issue is unfortunately quite reccurent).

**Comment by p-bo** [comment]
Well, no problem with .po files downloaded from Transifex - users aren't using them from there - crucial is, if you check it (and correct if necessary) after merging to sources, to haven't unusable files there and thus in hands of users.

**Comment by trasher** [comment]
We just retrieve files from Transifex, without any modification. If files are broken on transifex, they'll be broken in the app as well.
Checking every translation file is not an option; they have to be correct when retrieved.
