### ISSUE TITLE
Problem installing - plugin list empty

### ISSUE THREAD

**Issue by Keschyy** [pluginsGLPI/barcode#34]
Hi,
I just tried installing the barcode plugin.

GLPI version: 9.3.2

I tried the following steps:

> cd /var/www/html/glpi/plugins
git clone https://github.com/pluginsGLPI/barcode.git
mv barcode-master barcode
chown -R www-data:www-data barcode
chmod -R 755 barcode/ 

After I sign-out and sign-in again my plugin-list is completely empty.
If I delete the barcode folder all my other plugins show up again

I also tried the dev brach with similar results.

Any ideas how to fix the problem?

**Comment by cedric-anne** [comment]
Hi,

You may have to install dependencies using composer install command inside the Barcode plugin folder.

You can also download the .tar.bz2 archive of the release which contains the plugin build with its dependencies.

Regards

**Comment by Keschyy** [comment]
ohh - now i feel stupid.
pretty obvious actually :)

That worked like a charm.
Thank you
