### ISSUE TITLE
GLPI 9.3.2 - incompatiblilité

### ISSUE THREAD

**Issue by Sicoval31** [pluginsGLPI/barcode#37]
Bonjour,
Il semble que ce plugin est compatible avec toutes les versions >9.2 et <9.4.
Or, lorsque je copie le dossier dans le dossier plugin, je ne vois plus les plugins installés sous glpi.
Après suppression du dossier barcode, tout rentre dans l'ordre !

**Comment by cedric-anne** [comment]
Hi,

Maybe same problem as https://github.com/pluginsGLPI/barcode/issues/34.

Regards

**Comment by Sicoval31** [comment]
Merci, après téléchargemetn du tar.gz est decompression, le plugin est fonctionnel et GLPI aussi surtout :)
