### ISSUE TITLE
barcode	2.4.0 no work at GLPI 9.4.2

### ISSUE THREAD

**Issue by leangjia** [pluginsGLPI/barcode#44]
Hello. The barcode	2.4.0 no work at GLPI 9.4.2,Pls.

**Comment by cedric-anne** [comment]
Hi,

What is the error ? I tried yesterday and all works fine for me.

Regards

**Comment by papacharly974** [comment]
Hello.
Barcode 2.4.0 not work for me in glpi 9.4.2

When I copy the archive in /opt/glpi/plugin/barcode
the web page url/glpi/front/plugin.php don't show this plugin in the list !!!!!

**Comment by papacharly974** [comment]
Error with debug mode :
PHP Warning: require_once(/opt/glpi/plugins/barcode/vendor/autoload.php): failed to open stream: No such file or directory in /opt/glpi/plugins/barcode/setup.php at line 53

Fatal error: require_once(): Failed opening required '/opt/glpi/plugins/barcode/vendor/autoload.php' (include_path='.:/usr/share/php') in /opt/glpi/plugins/barcode/setup.php on line 53

**Comment by papacharly974** [comment]
It's OK now !!!!!!!!!!!!!
i downloded the source code !!!!
not the plugin ....
