### ISSUE TITLE
Wrong URL generated by the QRCode [GLPI9.4.2 | Barcode2.4]

### ISSUE THREAD

**Issue by thomsxm** [pluginsGLPI/barcode#48]
Hi, 
I'm not sure if it's normal or not, but the link that's generated by the QRCode is not the good one. 
![barcodeurl](https://user-images.githubusercontent.com/51754805/59366453-9e99a600-8d3a-11e9-8317-32b20ccb0428.jpg)

it's supposed to be : " http://[ip]/glpi/front/computer.form.php?id=1"

thanks,
Thom

**Comment by kungolfkjd** [comment]
Hi,
I confirm this issue on GLPI 9.4.2-1, barcode plugin 2.4.0.
Folder "/glpi/" gets duplicated to "/glpi/glpi/" in the URL generated for QRcode.
Fix would be very much appreciated, as GLPI relies on Apache aliasing, so URL rewrite is not an option.
Thanks - Chris

**Comment by ddurieux** [comment]
is the URL in configuration > general is right?

**Comment by kungolfkjd** [comment]
The URL in configuration > general is: 
http://our.domain.local/glpi
and system works OK

**Comment by cedric-anne** [comment]
Hi,

#50 should fix this.

Regards

**Comment by kungolfkjd** [comment]
Hi,
thank you very much for your help. 
Your code correction worked, now the URLs are OK.
Best regards - Chris
