### ISSUE TITLE
compatibility with 9.4.3

### ISSUE THREAD

**Issue by folletst** [pluginsGLPI/barcode#52]
Hello. Thank you for this plugin.
I ask you to help me. I've downloaded zip archive with this plugin and placed it to plugins folder: /var/www/html/glpi/plugins/barcode-master, renamed this folder to just "barcode". Using documentation of GLPI I logout and login to GLPI as administrator, but Plugin menu didn't appear. I can't install this plugin, because I do not have plugin menu :( I even set permissions 777 to plugin and barcode folders What can I check?

**Comment by folletst** [comment]
I created new topic on forum, i ask to help me with this plugin:
https://forum.glpi-project.org/viewtopic.php?id=171313

**Comment by sector7gp** [comment]
I just install the plugin in 9.4.3 and everything is fine, try to download the last release, not the code https://github.com/pluginsGLPI/barcode/releases/download/2.4.0/glpi-barcode-2.4.0.tar.bz2
