### ISSUE TITLE
Fatal Error on Generating QR Codes

### ISSUE THREAD

**Issue by Hyabusa1990** [pluginsGLPI/barcode#56]
I've got an fatal on creating QR Codes. I use GLPI 9.4.3 and barcode 2.4.

Here ist the Debug Log:

`Fatal error: Uncaught Error: Call to undefined method QRcode::png() in /var/www/html/plugins/barcode/inc/qrcode.class.php:159 Stack trace: #0 /var/www/html/plugins/barcode/inc/qrcode.class.php(380): PluginBarcodeQRcode->generateQRcode('Computer', '2', 1483400923, 0, Array) #1 /var/www/html/inc/massiveaction.class.php(991): PluginBarcodeQRcode::processMassiveActionsForOneItemtype(Object(MassiveAction), Object(Computer), Array) #2 /var/www/html/inc/massiveaction.class.php(970): MassiveAction->processForSeveralItemtypes() #3 /var/www/html/front/massiveaction.php(59): MassiveAction->process() #4 {main} thrown in /var/www/html/plugins/barcode/inc/qrcode.class.php on line 159`

**Comment by cedric-anne** [comment]
See #34
