### ISSUE TITLE
Installing the plugin on GLPI 9.4.5 blocks the plugin interface

### ISSUE THREAD

**Issue by Phaide** [pluginsGLPI/barcode#60]
Hi,

I tried installing the barcode plugin on a GLPI 9.4.5 server, but as soon as it is present in the plugins/ directory, the plugins web interface gets buggy and I cannot do anything :

![image](https://user-images.githubusercontent.com/33222654/71972542-241c0080-320d-11ea-8238-3f56865daaa0.png)

And as soon as I remove it, I can access the webpage normally.

I checked on another GLPI server, a newly installed one, and the issue remains.

Could you please take some time to update the plugin ?

Thank you very much :)
Shawn.

**Comment by stonebuzz** [comment]
Hi @Phaide can you check folder name and right ?

Can you check GLPI logs or Apache logs

Best regards

**Comment by cedric-anne** [comment]
Take a look at #34.

**Comment by Phaide** [comment]
Ooops !
Unpacking the bz2 solved the issue...
Sorry for the duplicate, and thank you for the support !
Best regards
