### ISSUE TITLE
Non-existent function: plugin_barcode_install plugin_barcode_check_config

### ISSUE THREAD

**Issue by fralla2** [pluginsGLPI/barcode#68]
Hi,

I tried to install version 2.5.0-rc3 on glpi 9.4.5 and got the following errors on the plugins' page : 

Non-existent function: plugin_barcode_install plugin_barcode_check_config
Non-existent function: plugin_barcode_uninstall

I've read on the glpi forum that someone else is having the same issue so it must be affecting everyones...

![image](https://user-images.githubusercontent.com/38400135/82452089-cf22ad80-9a7c-11ea-8c3e-67603d695b18.png)

Thanks

**Comment by cedric-anne** [comment]
Hi,

For GLPI 9.4, you should use plugin in version 2.4.1.

Regards

**Comment by sanjeevpandian** [comment]
I have tried installing Data injection on GLPI 9.4.5 and it's throwing the error in Plugin page



Non-existent function: plugin_datainjection_install plugin_datainjection_check_configNon-existent function: plugin_datainjection_uninstall

![Screenshot from 2023-01-05 15-29-42](https://user-images.githubusercontent.com/30174761/210753167-126ea0a5-6ca7-4282-9acd-e9f7c57f694f.png)

**Comment by cedric-anne** [comment]
GLPI 9.4.5 is not supported anymore.
