### ISSUE TITLE
Barcode generation not possible - GLPI v9.5.5 / Barcode v2.5.1

### ISSUE THREAD

**Issue by lorenzo8769** [pluginsGLPI/barcode#79]
Hi,

Barcode generation not possible - GLPI v9.5.5 / Barcode v2.5.1

Check LOG:
`/var/www/html/glpi/files/_log/php-errors.log`

[2021-06-25 08:56:50] glpiphplog.CRITICAL:   *** Uncaught Exception ParseError: syntax error, unexpected 'new' (T_NEW) in /var/www/html/glpi/marketplace/barcode/vendor/pear/image_barcode/Image/Barcode.php at line 80
  Backtrace :
  vendor/composer/ClassLoader.php:322                Composer\Autoload\includeFile()
  :                                                  Composer\Autoload\ClassLoader->loadClass()
  marketplace/barcode/inc/barcode.class.php:438      spl_autoload_call()
  marketplace/barcode/inc/barcode.class.php:294      PluginBarcodeBarcode->create()
  marketplace/barcode/inc/barcode.class.php:509      PluginBarcodeBarcode->printPDF()
  inc/massiveaction.class.php:1087                            PluginBarcodeBarcode::processMassiveActionsForOneItemtype()
  inc/massiveaction.class.php:1066                            MassiveAction->processForSeveralItemtypes()
  front/massiveaction.php:59                                    MassiveAction->process()

Check FILE at line 80:
`/var/www/html/glpi/marketplace/barcode/vendor/pear/image_barcode/Image/Barcode.php`

The  character "&" is not required. It must be removed for the generator to work.

Laurent

**Comment by cedric-anne** [comment]
Hi,

It has been fixed in version 2.5.2.

Regards
