### ISSUE TITLE
How to install

### ISSUE THREAD

**Issue by emersonschuede** [pluginsGLPI/barcode#8]
hi i dont find the plugin on  plugins list, need to run the setup php?

sorry for ask here but dont find in the wiki

**Comment by btry** [comment]
Hi

Check the plugin is installed correctly.

Glpi expects to find setup.php in glpi/plugins/barcode/
Barcode must be lower case.

Once you fixed this (i guess these requirements are not yet met), the plugin should appear in GLPI.

**Comment by emersonschuede** [comment]
Hello thanks for help, the folder was "barcode-master" after rename work's, but my version is 9.1.

exist some update for this version?

**Comment by btry** [comment]
No version available yet for GLPI 9.1.

If you have time you may submit a PR with changes to port the plugin to version 9.1 of GLPI.

**Comment by trasher** [comment]
Hi,

9.1 port has already been done in the develop branch; but consider it as not stable right now.

**Comment by emersonschuede** [comment]
how i can get this port version?

no problem if isnt stable now

Emerson Schuede
Analista de Suporte de TI | *AMARO*
emerson.schuede@amaro.com
T: +55 11 4063 6040 | R 8232
C: +55 11 97964 4281

2017-05-16 9:49 GMT-03:00 Johan Cwiklinski <notifications@github.com>:

**Comment by btry** [comment]
Go to the **Code**, then switch to the branch **develop**

![image](https://cloud.githubusercontent.com/assets/14139801/26113510/046a4f64-3a5b-11e7-88bc-a07c1c579564.png)

Now press the nice green button you already used 
![image](https://cloud.githubusercontent.com/assets/14139801/26113535/13ec8ca4-3a5b-11e7-9b4a-12899749c86a.png)

**Comment by emersonschuede** [comment]
Worked realy fine many thanks!

Emerson Schuede
Analista de Suporte de TI | *AMARO*
emerson.schuede@amaro.com
T: +55 11 4063 6040 | R 8232
C: +55 11 97964 4281

2017-05-16 12:14 GMT-03:00 btry <notifications@github.com>:
