### ISSUE TITLE
PHP Compile Error (64): when printing barcode

### ISSUE THREAD

**Issue by danicouso** [pluginsGLPI/barcode#83]
GLPI: 9.5.5
Barcode: 2.6.0

Hello, when printing a barcode in any format I get the following error:

PHP Compile Error (64): Declaration of & Image_Barcode_ean13::draw($text, $imgtype = 'png') must be compatible with & Image_Barcode::draw($text, $type = 'int25', $imgtype = 'png', $bSendToBrowser = true, $height = 60, $barwidth = 1) in /var/www/html/glpi/plugins/barcode/vendor/pear/image_barcode/Image/Barcode/ean13.php at line 156

It is with the default configuration, the QR works perfectly. PDF is generated blank

Thank you very much for your time. Regards, Daniel

**Comment by cedric-anne** [comment]
Fixed in latest release.
