### ISSUE TITLE
Enhanced barcode in GLPI 9.1.3.

### ISSUE THREAD

**Issue by hwchai78** [pluginsGLPI/barcode#9]
Hi, can it possible upgrade the plugin can used in GLPI 9.1.3 or above?
Thanks.

**Comment by fpusersuggest** [comment]
it would be very appreciated

**Comment by kernel52** [comment]
I would be very happy to assist in the creation of the 9.1.x version of the barcode, but I am not sure I can identify the changes that are needed.

**Comment by trasher** [comment]
The plugin is now available for GLPI 9.2; a 9.1 compatibility is not planned.

**Comment by kernel52** [comment]
True true. Tech moves forward. Is just a pitty that not all plugins work at the same version. I am planning to give the 9.1 dev a try. I will probably fail miserably but I might as well learn how to make my own plugins for GLPI :) 
Any suggestions are more than welcome. But thanks for your work in any case, is really helpful :)

**Comment by trasher** [comment]
Remember GLPI 9.1 is going EOL very soon... :)
